import type { Metadata } from "next";
import { BriefcaseBusiness } from "lucide-react";
import { profile } from "@/data/profile";
import { skillGroups } from "@/data/skills";
import { experiences } from "@/data/experience";
export const metadata: Metadata = { title: "About" };
export default function AboutPage() { return <>
 <section className="page-top"><div className="shell"><div className="eyebrow">A little context</div><h1>About me</h1><p className="muted" style={{ maxWidth: 590, margin: 0 }}>The person behind the projects: what I’m learning, what I care about, and where I hope to go next.</p></div></section>
 <section className="section"><div className="shell about-grid" style={{ display: "grid", gridTemplateColumns: ".8fr 1.2fr", gap: 72 }}><div><div className="eyebrow">Introduction</div><h2 className="section-title">Curious by nature.<br/>Developer by practice.</h2></div><div><p className="muted" style={{ fontSize: 16, marginTop: 0 }}>{profile.bio}</p><p className="muted">I’m currently studying {profile.education.faculty.toLowerCase()} at {profile.education.institution}. I’m especially interested in {profile.interests.join(", ").toLowerCase()}, and I’m working toward a career where I can help shape products from early ideas through polished, accessible interfaces.</p><p className="muted">My goal is to join a thoughtful team, contribute with curiosity and care, and keep building the technical judgment that comes from solving real problems.</p><div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 22 }}>{profile.interests.map(i=><span key={i} className="tag">{i}</span>)}</div></div></div></section>
 <section style={{ background: "var(--mist)", paddingBlock: 82 }}><div className="shell"><div className="eyebrow">Learning path</div><h2 className="section-title">Education</h2><div style={{ marginTop: 30, borderLeft: "1px solid #bac8d8", paddingLeft: 26, position: "relative", maxWidth: 720 }}><span style={{ width: 11, height: 11, borderRadius: "50%", background: "var(--blue)", position: "absolute", left: -6, top: 5 }}/><div style={{ display: "flex", justifyContent: "space-between", gap: 18, flexWrap: "wrap" }}><div><div style={{ fontSize: 19, fontWeight: 700 }}>{profile.education.institution}</div><div className="muted" style={{ marginTop: 6 }}>{profile.education.faculty}</div><div className="muted" style={{ fontSize: 13, marginTop: 8 }}>{profile.education.note}</div></div><div style={{ textAlign: "right", color: "var(--blue)", fontSize: 12, fontWeight: 700 }}>{profile.education.period}<div style={{ color: "var(--muted)", fontWeight: 400, marginTop: 6 }}>{profile.education.location}</div></div></div></div></div></section>
 <section className="section"><div className="shell"><div className="eyebrow">What I’m learning</div><h2 className="section-title">Skills & tools</h2><p className="muted" style={{ marginTop: 0, maxWidth: 540 }}>Starter content: review these example skills and keep only the tools you can confidently discuss.</p><div className="skill-grid" style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 28, marginTop: 36 }}>{skillGroups.map(g=><div key={g.name}><h3 style={{ fontSize: 13, margin: "0 0 15px", display: "flex", alignItems: "center", gap: 9 }}><span style={{ width: 6, height: 6, borderRadius: "50%", background: "var(--blue)" }}/>{g.name}</h3><div style={{ display: "grid", gap: 10 }}>{g.skills.map(s=><div key={s} style={{ borderBottom: "1px solid var(--line)", paddingBottom: 9, fontSize: 13, color: "#526277" }}>{s}</div>)}</div></div>)}</div></div></section>
 <section style={{ background: "var(--mist)", paddingBlock: 82 }}><div className="shell"><div className="eyebrow">Where I’ve contributed</div><h2 className="section-title">Experience</h2><div style={{ marginTop: 28, display: "grid", gap: 24 }}>{experiences.map((e,i)=><article key={i} className="experience-item" style={{ display: "grid", gridTemplateColumns: "190px 1fr", gap: 26, borderTop: "1px solid var(--line)", paddingTop: 23 }}><div style={{ color: "var(--blue)", fontSize: 12, fontWeight: 700 }}>{e.date}</div><div><div style={{ display: "flex", gap: 9, alignItems: "center" }}><BriefcaseBusiness size={16} color="var(--blue)"/><h3 style={{ margin: 0, fontSize: 18 }}>{e.role}</h3></div><div className="muted" style={{ fontSize: 13, marginTop: 6 }}>{e.organization}</div><p className="muted" style={{ fontSize: 13 }}>{e.description}</p><ul className="muted" style={{ fontSize: 13, paddingLeft: 18 }}>{e.responsibilities.map(r=><li key={r} style={{ marginBottom: 5 }}>{r}</li>)}</ul><div style={{ display: "flex", flexWrap: "wrap", gap: 7 }}>{e.technologies.map(t=><span className="tag" key={t}>{t}</span>)}</div></div></article>)}</div></div></section>
 
 </>; }
