import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowUpRight, Github } from "lucide-react";
import { projects } from "@/data/projects";

export function generateStaticParams() { return projects.map(p => ({ slug: p.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const p = projects.find(x=>x.slug===slug); return p ? { title: p.title, description: p.description } : {}; }
export default async function ProjectDetail({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const p = projects.find(x=>x.slug===slug); if (!p) notFound(); return <>
 <section className="page-top"><div className="shell"><Link href="/works" className="nav-link" style={{ display: "inline-flex", gap: 7, alignItems: "center", marginBottom: 36 }}><ArrowLeft size={14}/> All projects</Link><div className="eyebrow">{p.category}</div><h1>{p.title}</h1><p className="muted" style={{ maxWidth: 600, margin: 0 }}>{p.description}</p></div></section>
 <section className="shell" style={{ paddingTop: 42 }}><div className="project-hero" style={{ minHeight: 330, background: "#e9eef6", display: "grid", placeItems: "center", position: "relative" }}><div style={{ inset: "12% 10%", position: "absolute", background: "linear-gradient(135deg,#fff,#f7f9fc)", border: "1px solid #cbd5e1", display: "grid", placeItems: "center" }}><span style={{ color: "#526782", fontWeight: 700, letterSpacing: ".16em" }}>{p.title.toUpperCase()} · PROJECT PREVIEW</span></div></div></section>
 <section className="section"><div className="shell detail-grid" style={{ display: "grid", gridTemplateColumns: "minmax(0,1fr) 280px", gap: 70 }}><div style={{ display: "grid", gap: 34 }}>{[ ["Overview", p.overview], ["Problem & motivation", p.problem], ["Solution", p.solution], ["Main features", p.features], ["My role", p.role], ["Challenges", p.challenges], ["Outcome", p.outcome] ].map(([heading,content])=>content && <section key={heading as string}><div className="eyebrow">{heading as string}</div>{Array.isArray(content) ? <ul className="muted" style={{ paddingLeft: 20 }}>{content.map(item=><li key={item} style={{ marginTop: 9 }}>{item}</li>)}</ul> : <p className="muted">{content as string}</p>}</section>)}</div><aside><div style={{ borderTop: "2px solid var(--ink)", paddingTop: 18 }}><div className="eyebrow">Project details</div><div style={{ marginTop: 20 }}><div style={{ fontSize: 11, color: "var(--muted)", marginBottom: 9 }}>Technologies</div><div style={{ display: "flex", gap: 7, flexWrap: "wrap" }}>{p.technologies.map(t=><span key={t} className="tag">{t}</span>)}</div></div><div style={{ display: "grid", gap: 11, marginTop: 26 }}>{p.github && <a className="btn btn-outline" href={p.github} target="_blank" rel="noreferrer">GitHub <Github size={15}/></a>}{p.demo && <a className="btn btn-primary" href={p.demo} target="_blank" rel="noreferrer">Live demo <ArrowUpRight size={15}/></a>}</div></div></aside></div></section>
 
 </>; }
